---
- name: Configure Docker on Deployserver
  hosts: server
  become: true

  tasks:
    - name: apt updating
      apt:
        update_cache: yes

    - name: Install Python 3 and Pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Installing Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Deploy the Image from DockerHub and Run as Container
      command: docker run -d -p 8080:8081 saigowtham2605/insureme:1.0
